STSAFE-A120_Accessory_authentication: STSE Certificate prints functions
STSE Certificate prints functions
STSecureElement Library » STSE Certificate
Functions
void stse_certificate_print_attribute (PLAT_I32 type)
void stse_certificate_print_signature_algorithm (PLAT_I32 type)
void stse_certificate_print_tag (PLAT_I32 tag)
void stse_certificate_print_elliptic_curve (PLAT_I32 type)
PLAT_I32 stse_certificate_print_integer (const PLAT_UI8 *value, PLAT_I32 size)
PLAT_I32 stse_certificate_print_bit_string (const PLAT_UI8 *value, PLAT_I32 size)
void stse_certificate_simple_parse_attribute (const PLAT_UI8 *p, stse_cert_attribute_t *attribute_st, const PLAT_UI8 **next_thing)
Detailed Description
Function Documentation
stse_certificate_print_attribute()
void stse_certificate_print_attribute (PLAT_I32 type)
Print the Attribute.
Parameters
[in] type internal type of Attribute
Definition at line 116 of file stse_certificate_prints.c.
References ATTR_C, ATTR_CN, ATTR_DN, ATTR_LN, ATTR_ON, ATTR_OUN, ATTR_SN, ATTR_SOPN, and ATTR_UID.
Referenced by stse_certificate_print_name().
stse_certificate_print_signature_algorithm()
void stse_certificate_print_signature_algorithm (PLAT_I32 type)
Print the Signature Algorithm.
Parameters
[in] type internal type of SignatureAlgorithm
Definition at line 91 of file stse_certificate_prints.c.
References SIG_ECDSA_SHA1, SIG_ECDSA_SHA224, SIG_ECDSA_SHA256, SIG_ECDSA_SHA384, and SIG_ECDSA_SHA512.
Referenced by stse_certificate_print_parsed_cert().
stse_certificate_print_tag()
void stse_certificate_print_tag (PLAT_I32 tag)
Print the TAG.
Parameters
[in] tag tag of ASN.1 TLV (got from stse_certificate_identify_ASN1_TLV)
Definition at line 27 of file stse_certificate_prints.c.
References TAG_BITSTRING, TAG_BOOLEAN, TAG_ENUMERATED, TAG_extensions, TAG_GeneralizedTime, TAG_IA5String, TAG_INTEGER, TAG_issuerUniqueID, TAG_NULL, TAG_OBJECT_IDENTIFIER, TAG_ObjectDescriptor, TAG_OCTETSTRING, TAG_PrintableString, TAG_SEQUENCE, TAG_SET, TAG_subjectUniqueID, TAG_UTCTime, TAG_UTF8String, and TAG_x509VERSION.
stse_certificate_print_elliptic_curve()
void stse_certificate_print_elliptic_curve (PLAT_I32 type)
Print the Elliptic Curve Name.
Parameters
[in] type internal type of EllipticCurve
Definition at line 153 of file stse_certificate_prints.c.
References EC_bp256r1, EC_bp256t1, EC_bp384r1, EC_bp384t1, EC_bp512r1, EC_bp512t1, EC_P256, EC_P384, and EC_P521.
Referenced by stse_certificate_print_parsed_cert().
stse_certificate_print_integer()
PLAT_I32 stse_certificate_print_integer (const PLAT_UI8 * value, PLAT_I32 size)
Print an INTEGER.
Parameters
[in] *value pointer to the value of a INTEGER (got from stse_certificate_identify_ASN1_TLV)
[in] size size (in bytes) of the value field of this INTEGER (got from stse_certificate_identify_ASN1_TLV)
Return values
0 Success
-1 Failure. The INTEGER is negative, and \ this implementation doesn't support it
Definition at line 211 of file stse_certificate_prints.c.
stse_certificate_print_bit_string()
PLAT_I32 stse_certificate_print_bit_string (const PLAT_UI8 * value, PLAT_I32 size)
Print a BITSTRING.
Parameters
[in] *value pointer to the value of a BITSTRING (got from stse_certificate_identify_ASN1_TLV)
[in] size size (in bytes) of the value field of this BITSTRING (got from stse_certificate_identify_ASN1_TLV)
Return values
0 Success
-1 Failure. The bitstring excludes some of the LSBits of the LSB, which \ this implementation doesn't support
Definition at line 190 of file stse_certificate_prints.c.
Referenced by stse_certificate_print_name().
stse_certificate_simple_parse_attribute()
void stse_certificate_simple_parse_attribute (const PLAT_UI8 * p, stse_cert_attribute_t * attribute_st, const PLAT_UI8 ** next_thing)
Parse a Name Attribute.
Parameters
[in] *p pointer to the Name Attribute SET to be parsed
[out] *attribute_st pointer to stse_cert_attribute_t structure that will be filled
[out] **next_thing output pointer to next TLV
Note
partial parse function (for printing only)
Definition at line 281 of file stse_certificate_prints.c.
References attribute_st::str, attribute_st::strFormat, attribute_st::strSize, stse_certificate_identify_ASN1_TLV(), stse_certificate_identify_attribute(), TAG_OBJECT_IDENTIFIER, TAG_SEQUENCE, TAG_SET, and attribute_st::type.
Referenced by stse_certificate_print_name().