STSAFE-A120_Accessory_authentication: STSE Device Management
STSE Device Management
STSecureElement Library » API layer
Functions
stse_ReturnCode_t stse_init (stse_Handler_t *pSTSE)
stse_ReturnCode_t stse_device_reset (stse_Handler_t *pSTSE)
stse_ReturnCode_t stse_device_enter_hibernate (stse_Handler_t *pSTSE, stsafea_hibernate_wake_up_mode_t wake_up_mode)
stse_ReturnCode_t stse_device_power_on (stse_Handler_t *pSTSE)
stse_ReturnCode_t stse_device_power_off (stse_Handler_t *pSTSE)
stse_ReturnCode_t stse_device_echo (stse_Handler_t *pSTSE, PLAT_UI8 *pIn, PLAT_UI8 *pOut, PLAT_UI16 size)
stse_ReturnCode_t stse_device_lock (stse_Handler_t *pSTSE, PLAT_UI8 *pPassword, PLAT_UI8 password_length)
stse_ReturnCode_t stse_device_unlock (stse_Handler_t *pSTSE, PLAT_UI8 *pPassword, PLAT_UI8 password_length)
stse_ReturnCode_t stse_device_get_command_count (stse_Handler_t *pSTSE, PLAT_UI8 *record_count)
stse_ReturnCode_t stse_device_get_command_AC_records (stse_Handler_t *pSTSE, PLAT_UI8 record_count, stse_cmd_authorization_CR_t *pChange_rights, stse_cmd_authorization_record_t *pRecord_table)
stse_ReturnCode_t stse_device_get_life_cycle_state (stse_Handler_t *pSTSE, stsafea_life_cycle_state_t *pLife_cycle_state)
Detailed Description
The Application Programming Interface (API) layer is the entry point for the upper system application layer.
It provides high level functions to the application layer for secure element management.
Function Documentation
stse_init()
stse_ReturnCode_t stse_init (stse_Handler_t * pSTSE)
Initialize target device.
This function call the handler initialization function from core layer to initialize STSAFE handler in argument
Parameters
[in] pSTSE Pointer to STSAFE Handler
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 28 of file stse_device_management.c.
stse_device_reset()
stse_ReturnCode_t stse_device_reset (stse_Handler_t * pSTSE)
Reset target device.
This function call reset service to reset the device
Parameters
[in] pSTSE Pointer to STSAFE Handler
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 208 of file stse_device_management.c.
References stsafea_reset().
stse_device_enter_hibernate()
stse_ReturnCode_t stse_device_enter_hibernate (stse_Handler_t * pSTSE, stsafea_hibernate_wake_up_mode_t wake_up_mode)
Put target device in hibernate mode.
This function call hibernate service to put the device in hibernate
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] wake_up_mode Event to wake up from, listed in enum stsafea_hibernate_wake_up_mode_t
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 79 of file stse_device_management.c.
References stsafea_hibernate().
stse_device_power_on()
stse_ReturnCode_t stse_device_power_on (stse_Handler_t * pSTSE)
Power-on target device.
This function power-on the target device
Parameters
[in] pSTSE Pointer to STSAFE Handler
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 85 of file stse_device_management.c.
stse_device_power_off()
stse_ReturnCode_t stse_device_power_off (stse_Handler_t * pSTSE)
Power-off target device.
This function power-off the target device
Parameters
[in] pSTSE Pointer to STSAFE Handler
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Please refer to stse_device_power_on()
Definition at line 107 of file stse_device_management.c.
stse_device_echo()
stse_ReturnCode_t stse_device_echo (stse_Handler_t * pSTSE, PLAT_UI8 * pIn, PLAT_UI8 * pOut, PLAT_UI16 size)
Send echo command.
This function call send service to send an echo command
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] pIn Pointer to data buffer to be sent
[out] pOut Pointer to received data buffer
[in] size Size in bytes of pIn buffer
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
int main (void)
{
    stsafe_ReturnCode_t stsafe_ret;
    PLAT_UI16 echo_length = 4;
    PLAT_UI8  echo_send_buffer[echo_length] = {0x00, 0x11, 0x22, 0x33};
    PLAT_UI8  echo_recv_buffer[echo_length];
    stsafe_allocate_handler(stsafe_handler);
    stsafe_handler.io.BusType = STSAFE_BUS_TYPE_I2C;
    stsafe_handler.io.Busaddr = 3;
    stsafe_handler.io.Devaddr = 0x20;
    stsafe_ret = stsafe_init(&stsafe_handler);
    stsafe_ret = stsafe_se_echo(&stsafe_handler,
                                echo_send_buffer,
                                echo_recv_buffer,
                                echo_length);
}
See also
stsafe_echo()
Definition at line 126 of file stse_device_management.c.
References stsafea_echo().
stse_device_lock()
stse_ReturnCode_t stse_device_lock (stse_Handler_t * pSTSE, PLAT_UI8 * pPassword, PLAT_UI8 password_length)
Lock target device.
This function lock the target device using the password in argument
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] pPassword Pointer to the password buffer
[in] password_length Length of the password buffer in bytes
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
int main (void)
{
    stsafe_ReturnCode_t stsafe_ret;
    stsafe_allocate_handler(stsafe_handler);
    stsafe_handler.io.BusType = STSAFE_BUS_TYPE_I2C;
    stsafe_handler.io.Busaddr = 3;
    stsafe_handler.io.Devaddr = 0x20;
    stsafe_ret = stsafe_init(&stsafe_handler);
    PLAT_UI8 password[STSAFE_PASSWORD_LENGTH] = { ... };
    stsafe_ret = stsafe_se_lock(&stsafe_handler,
                                password,
                                STSAFE_PASSWORD_LENGTH);
}
See also
stsafe_verify_password()
stsafe_put_life_cyle_state()
Definition at line 131 of file stse_device_management.c.
stse_device_unlock()
stse_ReturnCode_t stse_device_unlock (stse_Handler_t * pSTSE, PLAT_UI8 * pPassword, PLAT_UI8 password_length)
Unlock target device.
This function unlock the target device using the password in argument
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] pPassword Pointer to the password buffer
[in] password_length Length of the password buffer in bytes
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
int main (void)
{
    stsafe_ReturnCode_t stsafe_ret;
    stsafe_allocate_handler(stsafe_handler);
    stsafe_handler.io.BusType = STSAFE_BUS_TYPE_I2C;
    stsafe_handler.io.Busaddr = 3;
    stsafe_handler.io.Devaddr = 0x20;
    stsafe_ret = stsafe_init(&stsafe_handler);
    PLAT_UI8 password[STSAFE_PASSWORD_LENGTH] = { ... };
    stsafe_ret = stsafe_se_unlock(&stsafe_handler,
                                  password,
                                  STSAFE_PASSWORD_LENGTH);
}
See also
stsafe_verify_password()
stsafe_put_life_cyle_state()
Definition at line 169 of file stse_device_management.c.
stse_device_get_command_count()
stse_ReturnCode_t stse_device_get_command_count (stse_Handler_t * pSTSE, PLAT_UI8 * record_count)
Return the record count of command access conditions.
This function query the access conditions of the target device command set and return the number of records
Parameters
[in] pSTSE Pointer to STSAFE Handler
[out] record_count Command authorization records count
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Please refer to stse_device_get_command_AC()
Definition at line 214 of file stse_device_management.c.
stse_device_get_command_AC_records()
stse_ReturnCode_t stse_device_get_command_AC_records (stse_Handler_t * pSTSE, PLAT_UI8 record_count, stse_cmd_authorization_CR_t * pChange_rights, stse_cmd_authorization_record_t * pRecord_table)
Return the command access conditions and change right.
This function query the access conditions of the target device command set
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] record_count Command authorization records count
[out] pChange_rights Pointer to change rights structure of the commands AC and host encrytpion flag
[out] pRecord_table Command authorization records table
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description
Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
int main (void)
{
    stsafe_ReturnCode_t stsafe_ret;
    stsafe_allocate_handler(stsafe_handler);
    stsafe_handler.io.BusType = STSAFE_BUS_TYPE_I2C;
    stsafe_handler.io.Busaddr = 3;
    stsafe_handler.io.Devaddr = 0x20;
    stsafe_ret = stsafe_init(&stsafe_handler);
    uint8_t cmd_authorization_record_count;
    cmd_authorization_CR_t command_auth_CR;
    stsafe_se_get_command_AC_count(&stsafe_handler, &cmd_authorization_record_count);
    cmd_authorization_record_t pCommand_auth_config[cmd_authorization_record_count];
    stsafe_ret = stsafe_se_get_command_AC(&stsafe_handler,
                                          cmd_authorization_record_count,
                                          &command_auth_CR,
                                          pCommand_auth_config);
}
See also
stsafe_query()
Definition at line 221 of file stse_device_management.c.
stse_device_get_life_cycle_state()
stse_ReturnCode_t stse_device_get_life_cycle_state (stse_Handler_t * pSTSE, stsafea_life_cycle_state_t * pLife_cycle_state)
Return the command access conditions and change right.
This function query the access conditions of the target device command set
Parameters
[in] pSTSE Pointer to STSAFE Handler
[out] pLife_cycle_state Pointer to stsafea_life_cycle_state_t variable to be updated
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 229 of file stse_device_management.c.
References stsafea_query_life_cycle_state().