STSAFE-A120_Accessory_authentication: STSE Symmetric key management
STSE Symmetric key management
STSecureElement Library » API layer
Functions
stse_ReturnCode_t stse_host_key_provisioning (stse_Handler_t *pSTSE, stsafea_host_key_type_t host_ecc_key_type, stsafea_host_keys_t *host_keys)
stse_ReturnCode_t stse_host_key_provisioning_wrapped (stse_Handler_t *pSTSE, stsafea_host_key_type_t host_key_type, stsafea_host_keys_t *host_keys, stse_ecc_key_type_t ecdhe_key_type)
stse_ReturnCode_t stse_host_key_provisioning_wrapped_authenticated (stse_Handler_t *pSTSE, stsafea_host_key_type_t host_key_type, stsafea_host_keys_t *host_keys, stse_ecc_key_type_t ecdhe_key_type, PLAT_UI8 signature_public_key_slot_number, stse_hash_algorithm_t signature_hash_algo, stse_ecc_key_type_t signature_private_key_type, PLAT_UI8 *signature_private_key)
stse_ReturnCode_t stse_get_symmetric_key_slots_count (stse_Handler_t *pSTSE, PLAT_UI8 *pSymmetric_key_slot_count)
stse_ReturnCode_t stse_get_symmetric_key_slot_info (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, stsafea_symmetric_key_slot_information_t *pSymmetric_key_slot_info)
stse_ReturnCode_t stse_get_symmetric_key_table_info (stse_Handler_t *pSTSE, PLAT_UI16 total_slot_count, stsafea_symmetric_key_slot_information_t *symmetric_key_table_info)
stse_ReturnCode_t stse_get_symmetric_key_slot_provisioning_ctrl_fields (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, stsafea_symmetric_key_slot_provisioning_ctrl_fields_t *pCtrl_fields)
stse_ReturnCode_t stse_write_symmetric_key_plaintext (stse_Handler_t *pSTSE, PLAT_UI8 *pKey, stsafea_generic_key_information_t *key_info)
stse_ReturnCode_t stse_write_symmetric_key_wrapped (stse_Handler_t *pSTSE, PLAT_UI8 *pKey, stsafea_generic_key_information_t *key_info, stse_ecc_key_type_t kek_session_ecc_type)
stse_ReturnCode_t stse_write_symmetric_key_wrapped_authenticated (stse_Handler_t *pSTSE, PLAT_UI8 *pKey, stsafea_generic_key_information_t *key_info, stse_ecc_key_type_t kek_session_ecc_type, PLAT_UI8 signature_public_key_slot_number, stse_hash_algorithm_t signature_hash_algo, stse_ecc_key_type_t signature_private_key_type, PLAT_UI8 *signature_private_key)
stse_ReturnCode_t stse_establish_symmetric_key (stse_Handler_t *pSTSE, stse_ecc_key_type_t ecc_key_type, PLAT_UI8 key_infos_count, stsafea_generic_key_information_t *key_infos_list, PLAT_UI8 *key_list)
stse_ReturnCode_t stse_establish_symmetric_key_authenticated (stse_Handler_t *pSTSE, stse_ecc_key_type_t key_type, PLAT_UI8 key_infos_count, stsafea_generic_key_information_t *key_infos_list, PLAT_UI8 *key_list, PLAT_UI8 signature_public_key_slot_number, stse_hash_algorithm_t hash_algo, stse_ecc_key_type_t private_key_type, PLAT_UI8 *private_key)
Detailed Description
The Application Programming Interface (API) layer is the entry point for the upper system application layer.
It provides high level functions to the application layer for symmetric symemtric key management on target STMicroelectronics Secure element device .
Function Documentation
stse_host_key_provisioning()
stse_ReturnCode_t stse_host_key_provisioning (stse_Handler_t * pSTSE, stsafea_host_key_type_t host_ecc_key_type, stsafea_host_keys_t * host_keys)
Host key provisioning in plaintext.
This API perform host key provisioning in plaintext,
it use the put attribute command if the device isn't a STSAFE-A120
and it use the "write host key" command if it is a STSAFE-A120
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] host_ecc_key_type Key type
[in] host_keys Pointer to the key structure
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description
Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx devices during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
See also
stsafe_init
Definition at line 487 of file stse_symmetric_keys_management.c.
References STSAFE_A120, stsafea_host_key_provisioning(), and STSE_SERVICE_HANDLER_NOT_INITIALISED.
stse_host_key_provisioning_wrapped()
stse_ReturnCode_t stse_host_key_provisioning_wrapped (stse_Handler_t * pSTSE, stsafea_host_key_type_t host_key_type, stsafea_host_keys_t * host_keys, stse_ecc_key_type_t ecdhe_key_type)
Host key provisioning wrapped.
This API perform host key provisioning with the key wrapped using a volatile KEK session
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] host_key_type Key type
[in] host_keys Pointer to the key structure
[in] ecdhe_key_type ECC key type to use in KEK session
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 522 of file stse_symmetric_keys_management.c.
References STSAFE_A120, STSE_API_HANDLER_NOT_INITIALISED, and STSE_COMMAND_CODE_NOT_SUPPORTED.
stse_host_key_provisioning_wrapped_authenticated()
stse_ReturnCode_t stse_host_key_provisioning_wrapped_authenticated (stse_Handler_t * pSTSE, stsafea_host_key_type_t host_key_type, stsafea_host_keys_t * host_keys, stse_ecc_key_type_t ecdhe_key_type, PLAT_UI8 signature_public_key_slot_number, stse_hash_algorithm_t signature_hash_algo, stse_ecc_key_type_t signature_private_key_type, PLAT_UI8 * signature_private_key)
Host key provisioning wrapped and authenticated.
This API perform host key provisioning with the key wrapped using an authenticated volatile KEK session
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] host_key_type Key type
[in] host_keys Pointer to the key structure
[in] ecdhe_key_type ECC key type to use in KEK session
[in] signature_public_key_slot_number Slot number of the public key used in authentication
[in] signature_hash_algo Hash algo used for the signature digest
[in] signature_private_key_type Key type of the private key used in authentication
[in] signature_private_key Private key used in authentication
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 613 of file stse_symmetric_keys_management.c.
References STSAFE_A120, STSE_API_HANDLER_NOT_INITIALISED, and STSE_COMMAND_CODE_NOT_SUPPORTED.
stse_get_symmetric_key_slots_count()
stse_ReturnCode_t stse_get_symmetric_key_slots_count (stse_Handler_t * pSTSE, PLAT_UI8 * pSymmetric_key_slot_count)
Get symmetric key slot count.
Get the number of slot in symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[out] pSymmetric_key_slot_count Number of slot in symmetric key table
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 718 of file stse_symmetric_keys_management.c.
References stsafea_query_symmetric_key_slots_count(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_get_symmetric_key_slot_info()
stse_ReturnCode_t stse_get_symmetric_key_slot_info (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, stsafea_symmetric_key_slot_information_t * pSymmetric_key_slot_info)
Get one symmetric key slot info.
Get the informations of one slot in symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Slot number to get the information
[out] pSymmetric_key_slot_info Buffer to store the information structure
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 730 of file stse_symmetric_keys_management.c.
stse_get_symmetric_key_table_info()
stse_ReturnCode_t stse_get_symmetric_key_table_info (stse_Handler_t * pSTSE, PLAT_UI16 total_slot_count, stsafea_symmetric_key_slot_information_t * symmetric_key_table_info)
Get symmetric key slot info.
Get the informations of all slot of symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] total_slot_count Target Device total symmetric key slots number
[out] symmetric_key_table_info Buffer to store the information structure list for all slots
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 771 of file stse_symmetric_keys_management.c.
stse_get_symmetric_key_slot_provisioning_ctrl_fields()
stse_ReturnCode_t stse_get_symmetric_key_slot_provisioning_ctrl_fields (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, stsafea_symmetric_key_slot_provisioning_ctrl_fields_t * pCtrl_fields)
Get symmetric key slot provisioning control fields.
Get symmetric key slot provisioning control fields
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Slot number of the slot to query
[out] pCtrl_fields Output structure for the provisioning control fields of the target slot
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 784 of file stse_symmetric_keys_management.c.
References STSE_API_HANDLER_NOT_INITIALISED.
stse_write_symmetric_key_plaintext()
stse_ReturnCode_t stse_write_symmetric_key_plaintext (stse_Handler_t * pSTSE, PLAT_UI8 * pKey, stsafea_generic_key_information_t * key_info)
Write symmetric key plaintext in stsafe symmetric key table.
This API Write a symmetric key in stsafe symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] pKey Key material to write in STSAFE
[in] key_info Key information used to populate the symmetric key table
[in] kek_session_ecc_type Key type to use in volatile KEK session
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 797 of file stse_symmetric_keys_management.c.
References stsafea_write_symmetric_key_plaintext(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_write_symmetric_key_wrapped()
stse_ReturnCode_t stse_write_symmetric_key_wrapped (stse_Handler_t * pSTSE, PLAT_UI8 * pKey, stsafea_generic_key_information_t * key_info, stse_ecc_key_type_t kek_session_ecc_type)
Write symmetric key wrapped in stsafe symmetric key table.
This API Write a symmetric key in stsafe symmetric key table inside a volatile KEK session
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] pKey Key material to write in STSAFE
[in] key_info Key information used to populate the symmetric key table
[in] kek_session_ecc_type Key type to use in volatile KEK session
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 812 of file stse_symmetric_keys_management.c.
References STSE_API_HANDLER_NOT_INITIALISED.
stse_write_symmetric_key_wrapped_authenticated()
stse_ReturnCode_t stse_write_symmetric_key_wrapped_authenticated (stse_Handler_t * pSTSE, PLAT_UI8 * pKey, stsafea_generic_key_information_t * key_info, stse_ecc_key_type_t kek_session_ecc_type, PLAT_UI8 signature_public_key_slot_number, stse_hash_algorithm_t signature_hash_algo, stse_ecc_key_type_t signature_private_key_type, PLAT_UI8 * signature_private_key)
Authenticated write symmetric key in stsafe symmetric key table.
This API Write a symmetric key in stsafe symmetric key table inside an authenticated volatile KEK session
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] pKey Key material to write in STSAFE
[in] key_info Key information used to populate the symmetric key table
[in] kek_session_ecc_type Key type to use in volatile KEK session
[in] signature_public_key_slot_number Slot number of the public key used in authentication
[in] signature_hash_algo Hash algo used for the signature digest
[in] signature_private_key_type Key type of the private key used in authentication
[in] signature_private_key Private key used in authentication
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description
Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx devices during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stsafe_ReturnCode_t stsafe_ret;
/* - ECB 128 bits key and it corresponding info */
PLAT_UI8 key_value[STSAFE_AES_128_KEY_SIZE] = {0x00,0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99,0xAA,0xBB,0xCC,0xDD,0xEE,0xFF};
stsafe_generic_key_information_t key_info = {0};
key_info.lock_indicator = 0;
key_info.record.slot_number = 3;
key_info.record.type = STSAFE_SYMMETRIC_KEY_TYPE_AES_128;
key_info.record.mode_of_operation = STSAFE_KEY_OPERATION_MODE_ECB;
key_info.record.usage.encryption = 1;
key_info.record.usage.decryption = 1;
key_info.length[1] = STSAFE_KEY_INFORMATION_LENGTH_ECB;
stsafe_ret = stsafe_write_symmetric_key(
        pSTSAFE,
        key_value,
        &key_info,
        STSAFE_ECC_KT_NIST_P_256);
See also
stsafe_init
Definition at line 885 of file stse_symmetric_keys_management.c.
References STSAFE_A120, STSE_API_HANDLER_NOT_INITIALISED, and STSE_COMMAND_CODE_NOT_SUPPORTED.
stse_establish_symmetric_key()
stse_ReturnCode_t stse_establish_symmetric_key (stse_Handler_t * pSTSE, stse_ecc_key_type_t ecc_key_type, PLAT_UI8 key_infos_count, stsafea_generic_key_information_t * key_infos_list, PLAT_UI8 * key_list)
Establish symmetric key in stsafe symmetric key table.
This API establish one or more symmetric keys in stsafe symmetric key table through an ECDHE process
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] ecc_key_type Key type to use for the ECDHE
[in] key_infos_list Key information list used to populate the symmetric key table
[out] key_list Key list resulting of the ECDHE (OKM[1..N])
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description
Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx devices during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stsafe_ReturnCode_t stsafe_ret;
/* - ECB 128 bits key buffer and its corresponding info */
PLAT_UI8 key_buffer[STSAFE_AES_128_KEY_SIZE];
stsafe_generic_key_information_t key_info = {0};
key_info.lock_indicator = 0;
key_info.record.slot_number = 3;
key_info.record.type = STSAFE_SYMMETRIC_KEY_TYPE_AES_128;
key_info.record.mode_of_operation = STSAFE_KEY_OPERATION_MODE_ECB;
key_info.record.usage.encryption = 1;
key_info.record.usage.decryption = 1;
key_info.length[1] = STSAFE_KEY_INFORMATION_LENGTH_ECB;
stsafe_generic_key_information_list_t key_info_list;
key_info_list.key_count = 1;
key_info_list.length = STSAFE_KEY_INFORMATION_LENGTH_ECB + 2;
key_info_list.list = &key_info;
stsafe_ret = stsafe_establish_symmetric_key(
        pSTSAFE,
        STSAFE_ECC_KT_BP_P_512,
        &key_info_list,
        key_buffer);
See also
stsafe_init
Definition at line 974 of file stse_symmetric_keys_management.c.
stse_establish_symmetric_key_authenticated()
stse_ReturnCode_t stse_establish_symmetric_key_authenticated (stse_Handler_t * pSTSE, stse_ecc_key_type_t key_type, PLAT_UI8 key_infos_count, stsafea_generic_key_information_t * key_infos_list, PLAT_UI8 * key_list, PLAT_UI8 signature_public_key_slot_number, stse_hash_algorithm_t hash_algo, stse_ecc_key_type_t private_key_type, PLAT_UI8 * private_key)
Authenticated establish symmetric key in stsafe symmetric key table.
This API establish one or more symmetric keys in stsafe symmetric key table through an authenticated ECDHE process
Parameters
[in] pSTSE Pointer to STSE Handler
[in] key_type Key type to use for the ECDHE
[in] key_infos_list Key information list used to populate the symmetric key table
[out] key_list Key list resulting of the ECDHE (OKM[1..N])
[in] signature_public_key_slot_number Generic public key slot number used for the authentication
[in] hash_algo Hash algorithm ID used to hash the authentication digest
[in] private_key_type Key type of the authentication private key
[in] private_key Authentication private key buffer
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Description
Following diagram illustrates the interactions performed between the Host and the target STSAFE-A1xx devices during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stsafe_ReturnCode_t stsafe_ret;
/* - ECB 128 bits key buffer and its corresponding info */
PLAT_UI8 key_buffer[STSAFE_AES_128_KEY_SIZE];
stsafe_generic_key_information_t key_info = {0};
key_info.lock_indicator = 0;
key_info.record.slot_number = 3;
key_info.record.type = STSAFE_SYMMETRIC_KEY_TYPE_AES_128;
key_info.record.mode_of_operation = STSAFE_KEY_OPERATION_MODE_ECB;
key_info.record.usage.encryption = 1;
key_info.record.usage.decryption = 1;
key_info.length[1] = STSAFE_KEY_INFORMATION_LENGTH_ECB;
stsafe_generic_key_information_list_t key_info_list;
key_info_list.key_count = 1;
key_info_list.length = STSAFE_KEY_INFORMATION_LENGTH_ECB + 2;
key_info_list.list = &key_info;
stsafe_ret = stsafe_establish_symmetric_key(
        pSTSAFE,
        STSAFE_ECC_KT_BP_P_512,
        &key_info_list,
        key_buffer);
See also
stsafe_init
Definition at line 1100 of file stse_symmetric_keys_management.c.
References STSE_API_HANDLER_NOT_INITIALISED.