STSAFE-A120_Accessory_authentication: STSE Certificate parser
STSE Certificate parser
STSecureElement Library » STSE Certificate
Functions
void stse_certificate_init (stse_certificate_t *cert)
stse_ReturnCode_t stse_certificate_parse (const PLAT_UI8 *cert, stse_certificate_t *stse_certificate, const PLAT_UI8 **next)
stse_ReturnCode_t stse_certificate_is_valid (const stse_certificate_t *stse_certificate, const stse_cert_validity_t *currentTime)
stse_ReturnCode_t stse_certificate_is_CA (const stse_certificate_t *cert)
stse_ReturnCode_t stse_certificate_is_parent (const stse_certificate_t *parent, const stse_certificate_t *child, const stse_cert_validity_t *currentTime)
void stse_certificate_copy (stse_certificate_t *copiedCert, const stse_certificate_t *originalCert)
stse_ReturnCode_t stse_certificate_parse_chain (PLAT_UI8 *rootCA, PLAT_UI8 *certChain, PLAT_UI16 certChainSize, stse_certificate_t *leafCert)
void stse_certificate_set_stse_companion (stse_Handler_t *pSTSE)
Detailed Description
Enumeration Type Documentation
stse_certificate_tag_t
enum stse_certificate_tag_t
Definitions of X509 TAGs.
Enumerator
TAG_BOOLEAN
x509 tag for BOOLEAN
TAG_INTEGER
x509 tag for INTEGER
TAG_BITSTRING
x509 tag for BITSTRING
TAG_OCTETSTRING
x509 tag for OCTETSTRING
TAG_NULL
x509 tag for NULL
TAG_OBJECT_IDENTIFIER
x509 tag for OBJECT_IDENTIFIER
TAG_ObjectDescriptor
x509 tag for ObjectDescriptor
TAG_ENUMERATED
x509 tag for ENUMERATED
TAG_UTF8String
x509 tag for UTF8String
TAG_PrintableString
x509 tag for PrintableString
TAG_IA5String
x509 tag for IA5String
TAG_UTCTime
x509 tag for UTCTime
TAG_GeneralizedTime
x509 tag for GeneralizedTime
TAG_SEQUENCE
x509 tag for SEQUENCE
TAG_SET
x509 tag for SET
TAG_x509VERSION
x509 tag for x509VERSION
TAG_issuerUniqueID
x509 tag for issuerUniqueID
TAG_subjectUniqueID
x509 tag for subjectUniqueID
TAG_extensions
x509 tag for extensions
Definition at line 32 of file stse_certificate_types.h.
stse_certificate_signature_algorithms_t
enum stse_certificate_signature_algorithms_t
Definitions of available signature algorithms.
Enumerator
SIG_ECDSA_SHA1
ECDSA with SHA1 algorithm
SIG_ECDSA_SHA224
ECDSA with SHA224 algorithm
SIG_ECDSA_SHA256
ECDSA with SHA256 algorithm
SIG_ECDSA_SHA384
ECDSA with SHA384 algorithm
SIG_ECDSA_SHA512
ECDSA with SHA512 algorithm
Definition at line 55 of file stse_certificate_types.h.
stse_certificate_name_attributes_t
enum stse_certificate_name_attributes_t
Definitions of supported Name Attributes.
Enumerator
ATTR_CN
CommonName
ATTR_SN
SerialNumber
ATTR_C
Country
ATTR_LN
LocalityName
ATTR_SOPN
stateOrProvinceName
ATTR_ON
Organization Name
ATTR_OUN
Organization Unit Name
ATTR_UID
UniqueIdentifier
ATTR_DN
DistinguishedName
Definition at line 64 of file stse_certificate_types.h.
stse_certificate_elliptic_curves_t
enum stse_certificate_elliptic_curves_t
Definitions of supported Elliptic Curve Names.
Enumerator
EC_P256
NIST P-256
EC_P384
NIST P-384
EC_P521
NIST P-521
EC_bp256r1
brainpoolP256r1
EC_bp256t1
brainpoolP256t1
EC_bp384r1
brainpoolP384r1
EC_bp384t1
brainpoolP384t1
EC_bp512r1
brainpoolP512r1
EC_bp512t1
brainpoolP512t1
Definition at line 77 of file stse_certificate_types.h.
stse_certificate_extensions_type_t
enum stse_certificate_extensions_type_t
Definitions of supported Extensions types.
Enumerator
EXTENSION_KU
KeyUsage
EXTENSION_BC
BasicContrains
EXTENSION_EKU
extKeyUsage
Definition at line 90 of file stse_certificate_types.h.
Function Documentation
stse_certificate_init()
void stse_certificate_init (stse_certificate_t * cert)
Initialize a certificate (stse_certificate_t) to an empty one.
Parameters
[in,out] cert pointer to the stse_certificate_t to be initialized
Note
This functions should be called before parsing a certificate
Definition at line 132 of file stse_certificate.c.
References stse_internal_certificate::EllipticCurve, stse_internal_certificate::extensions, stse_internal_certificate::extensionsFlags, stse_internal_certificate::extensionsSize, stse_cert_public_key_t::fsize, stse_internal_certificate::issuer, stse_internal_certificate::issuerSize, ECDSAsign_st::pR, ECDSAsign_st::pS, stse_internal_certificate::PubKey, stse_cert_public_key_t::pX, stse_cert_public_key_t::pY, ECDSAsign_st::rSize, stse_internal_certificate::serialNumber, stse_internal_certificate::serialNumberSize, stse_internal_certificate::Sign, stse_internal_certificate::signature, stse_internal_certificate::SignatureAlgorithm, ECDSAsign_st::sSize, stse_internal_certificate::subject, stse_internal_certificate::subjectSize, stse_internal_certificate::tbs, stse_internal_certificate::tbsSize, stse_internal_certificate::validity, stse_internal_certificate::validitySize, and stse_internal_certificate::x509Version.
Referenced by stse_certificate_parse().
stse_certificate_parse()
stse_ReturnCode_t stse_certificate_parse (const PLAT_UI8 * cert, stse_certificate_t * stse_certificate, const PLAT_UI8 ** next)
Parse an x509 certificate.
Parameters
[in] cert pointer to the x509 certificate to be parsed
[out] stse_certificate pointer to the stse_certificate_t that will be filled
[out] next pointer to cert array after the parsed certificate (it can be NULL)
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Warning
The parsed certificated could be empty, it is necessary to call a function which verifies the certificate to be valid before using it.
Definition at line 171 of file stse_certificate.c.
References stse_certificate_identify_ASN1_TLV(), stse_certificate_init(), and TAG_SEQUENCE.
Referenced by stse_certificate_parse_chain().
stse_certificate_is_valid()
stse_ReturnCode_t stse_certificate_is_valid (const stse_certificate_t * stse_certificate, const stse_cert_validity_t * currentTime)
Check that an imported x509 certificate is valid.
Parameters
[in] stse_certificate pointer to the parsed x509 certificate to be validated
[in] currentTime pointer to a stse_cert_validity_t with the current DateTime. If NULL no date check is done
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Warning
If currentTime==NULL the check on the validity dates of the certificate will be bypassed.
Definition at line 216 of file stse_certificate.c.
References stse_internal_certificate::EllipticCurve, stse_cert_public_key_t::fsize, stse_internal_certificate::issuer, stse_internal_certificate::issuerSize, stse_internal_certificate::pPubKey_point_representation_id, ECDSAsign_st::pR, ECDSAsign_st::pS, stse_internal_certificate::PubKey, stse_cert_public_key_t::pX, stse_cert_public_key_t::pY, ECDSAsign_st::rSize, stse_internal_certificate::serialNumber, stse_internal_certificate::serialNumberSize, stse_internal_certificate::Sign, stse_internal_certificate::signature, stse_internal_certificate::SignatureAlgorithm, ECDSAsign_st::sSize, stse_internal_certificate::subject, stse_internal_certificate::subjectSize, stse_internal_certificate::validity, stse_internal_certificate::validitySize, and stse_internal_certificate::x509Version.
Referenced by stse_certificate_is_parent().
stse_certificate_is_CA()
stse_ReturnCode_t stse_certificate_is_CA (const stse_certificate_t * cert)
Check whether a certificate is marked as belonging to a CA.
Parameters
[in] *cert pointer to the parsed x509 certificate to be checked
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 254 of file stse_certificate.c.
References stse_internal_certificate::extensionsFlags, and STSE_OK.
stse_certificate_is_parent()
stse_ReturnCode_t stse_certificate_is_parent (const stse_certificate_t * parent, const stse_certificate_t * child, const stse_cert_validity_t * currentTime)
Check whether "parent" issued "child".
Parameters
[in] parent pointer to the parsed x509 certificate of the supposed issuer of child
[in] child pointer to the parsed x509 certificate of the certificated supposedly issued by parent
[in] currentTime pointer to a stse_cert_validity_t with the current DateTime. If NULL no date check is done.
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Note
RFC 5280 mandates an extremely expensive comparison, which we don't perform. As result of this simplification some legitimate parentship relation could be not acknowledged (the opposite should not occur).
Warning
This check only a single level parent relashion (i.e. whether parent issued child)
Definition at line 268 of file stse_certificate.c.
References stse_internal_certificate::issuer, stse_internal_certificate::issuerSize, stse_certificate_is_valid(), STSE_OK, stse_internal_certificate::subject, and stse_internal_certificate::subjectSize.
Referenced by stse_certificate_parse_chain().
stse_certificate_copy()
void stse_certificate_copy (stse_certificate_t * copiedCert, const stse_certificate_t * originalCert)
Copy a certificate (stse_certificate_t) into another structure.
Parameters
[out] copiedCert pointer to the stse_certificate_t that will be written
[out] originalCert pointer to the stse_certificate_t that will be copied
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 163 of file stse_certificate.c.
Referenced by stse_certificate_parse_chain().
stse_certificate_parse_chain()
stse_ReturnCode_t stse_certificate_parse_chain (PLAT_UI8 * rootCA, PLAT_UI8 * certChain, PLAT_UI16 certChainSize, stse_certificate_t * leafCert)
Iterate over the certificate chain in argument and check each child/parent pairs.
Parameters
[in] rootCA Pointer to the root CA certificate buffer
[in] certChain Pointer to the certificate chain buffer
[in] certChainSize Size of the certificate chain buffer
[out] leafCert Pointer to the leaf certificate structure
Returns
PLAT_I32 : 0 on success ; error code otherwise
Definition at line 393 of file stse_certificate.c.
References stse_certificate_copy(), stse_certificate_is_parent(), stse_certificate_parse(), and STSE_OK.
Referenced by stse_device_authenticate().
stse_certificate_set_stse_companion()
void stse_certificate_set_stse_companion (stse_Handler_t * pSTSE)
Assign the certificate parser STSAFE-A companion.
Parameters
[in] pSTSAFE Pointer to STSAFE handler
Definition at line 453 of file stse_certificate.c.