STSAFE-A120_Accessory_authentication: STSE Certificate subparsing routines
STSE Certificate subparsing routines
STSecureElement Library » STSE Certificate
Functions
PLAT_I32 stse_certificate_identify_ASN1_TLV (const PLAT_UI8 *asn1, PLAT_I32 *parsed, PLAT_I32 *size, const PLAT_UI8 **value)
PLAT_I32 stse_certificate_identify_attribute (const PLAT_UI8 *oid, PLAT_I32 size)
void stse_certificate_parse_ECDSA_signature (const PLAT_UI8 *signature, stse_certificate_t *stse_certificate, const PLAT_UI8 **next_thing)
void stse_certificate_parse_X509_version (const PLAT_UI8 *x509VersionField, stse_certificate_t *stse_certificate, const PLAT_UI8 **next_thing)
void stse_certificate_parse_signature_algorithm (const PLAT_UI8 *SA, PLAT_I32 *singatureAlgorithm, const PLAT_UI8 **next_thing)
void stse_certificate_parse_ECC_public_key (const PLAT_UI8 *EccPK, stse_certificate_t *stse_certificate, const PLAT_UI8 **next_thing)
void stse_certificate_parse_integer (const PLAT_UI8 *integer, const PLAT_UI8 **outp, PLAT_I32 *outSize, const PLAT_UI8 **next_thing)
void stse_certificate_parse_validity (const PLAT_UI8 *p, stse_cert_validity_t *notBefore_st, stse_cert_validity_t *notAfter_st, const PLAT_UI8 **next_thing)
void stse_certificate_parse_relative_distinguished_name (const PLAT_UI8 *p, const PLAT_UI8 **nextRDN, const PLAT_UI8 **attribute)
void stse_certificate_parse_attribute (const PLAT_UI8 *p, stse_cert_attribute_t *attribute_st, const PLAT_UI8 **next_thing)
PLAT_I32 stse_certificate_date_compare (const stse_cert_validity_t *D1, const stse_cert_validity_t *D2)
PLAT_I32 stse_certificate_count_attributes (const PLAT_UI8 *p)
PLAT_I32 stse_certificate_case_insensitive_compare (const PLAT_UI8 *p1, const PLAT_UI8 *p2, PLAT_I32 size)
PLAT_I32 stse_certificate_case_identify_extension (const PLAT_UI8 *oid, PLAT_I32 size)
void stse_certificate_parse_extension (const PLAT_UI8 *ext, PLAT_UI32 *extFlags, stse_cert_extension_t *ext_st)
PLAT_I32 stse_certificate_get_small_integer (const PLAT_UI8 *value, PLAT_I32 size)
Detailed Description
Function Documentation
stse_certificate_identify_ASN1_TLV()
PLAT_I32 stse_certificate_identify_ASN1_TLV (const PLAT_UI8 * asn1, PLAT_I32 * parsed, PLAT_I32 * size, const PLAT_UI8 ** value)
Identify the ASN.1 TLV.
Parameters
[in] *asn1 pointer to the ASN.1 TLV
[out] *parsed will contain the number of processed bytes (rarely used)
[out] *size will contain the size (in bytes) of the value field of this ASN.1 TLV
[out] **value will contain a pointer to the value field of this ASN.1 TLV
Returns
The internal TAG identifier of this TLV or -1 if failure
Definition at line 21 of file stse_certificate_subparsing.c.
References IS_VALID_TAG.
Referenced by stse_certificate_count_attributes(), stse_certificate_parse(), stse_certificate_parse_attribute(), stse_certificate_parse_ECC_public_key(), stse_certificate_parse_ECDSA_signature(), stse_certificate_parse_extension(), stse_certificate_parse_integer(), stse_certificate_parse_relative_distinguished_name(), stse_certificate_parse_signature_algorithm(), stse_certificate_parse_validity(), stse_certificate_parse_X509_version(), stse_certificate_print_name(), and stse_certificate_simple_parse_attribute().
stse_certificate_identify_attribute()
PLAT_I32 stse_certificate_identify_attribute (const PLAT_UI8 * oid, PLAT_I32 size)
Identify the Name Attribute from its OID.
Parameters
[in] *oid The value of the OID of the Attribute (got from stse_certificate_identify_ASN1_TLV)
[in] size size (in bytes) of the value field of this OID (got from stse_certificate_identify_ASN1_TLV)
Note
Only a very limited set of Attributes is supported
Returns
The internal type identifing the Attribute or -1 for failure
Definition at line 256 of file stse_certificate_subparsing.c.
References ATTR_C, ATTR_CN, ATTR_DN, ATTR_LN, ATTR_ON, ATTR_OUN, ATTR_SN, ATTR_SOPN, ATTR_UID, AttributeOID_st::len, AttributeOID_st::oid, and AttributeOID_st::type.
Referenced by stse_certificate_parse_attribute(), and stse_certificate_simple_parse_attribute().
stse_certificate_parse_ECDSA_signature()
void stse_certificate_parse_ECDSA_signature (const PLAT_UI8 * signature, stse_certificate_t * stse_certificate, const PLAT_UI8 ** next_thing)
Parse an ECDSA signature.
Parameters
[in] *signature pointer to the expected signature field of the x509 certificate
[out] *stse_certificate pointer to the stse_certificate_t that will be filled
[out] **next_thing will contain a pointer to the next TLV
Definition at line 83 of file stse_certificate_subparsing.c.
References ECDSAsign_st::pR, ECDSAsign_st::pS, ECDSAsign_st::rSize, stse_internal_certificate::Sign, ECDSAsign_st::sSize, stse_certificate_identify_ASN1_TLV(), stse_certificate_parse_integer(), TAG_BITSTRING, and TAG_SEQUENCE.
stse_certificate_parse_X509_version()
void stse_certificate_parse_X509_version (const PLAT_UI8 * x509VersionField, stse_certificate_t * stse_certificate, const PLAT_UI8 ** next_thing)
Parse the x509 Version of a certificate.
Parameters
[in] *x509VersionField pointer to the version field of a certificate
[out] *stse_certificate pointer to the stse_certificate_t that will be filled
[out] **next_thing output pointer to next TLV
Definition at line 168 of file stse_certificate_subparsing.c.
References stse_certificate_get_small_integer(), stse_certificate_identify_ASN1_TLV(), TAG_INTEGER, and stse_internal_certificate::x509Version.
stse_certificate_parse_signature_algorithm()
void stse_certificate_parse_signature_algorithm (const PLAT_UI8 * SA, PLAT_I32 * singatureAlgorithm, const PLAT_UI8 ** next_thing)
Parse a SignatureAlgorithm (or signature of a tbsCertificate)
Parameters
[in] *SA pointer to the SignatureAlgorithm (or signature of a tbsCertificate)
[out] *singatureAlgorithm integer that will be filled with the internal encoding of signatureAlgorithm
[out] **next_thing output pointer to next TLV
Note
Only a very limited set of SignatureAlgorithm is supported
Definition at line 131 of file stse_certificate_subparsing.c.
References SignatureAlgorithmOID_st::len, SignatureAlgorithmOID_st::oid, SIG_ECDSA_SHA1, SIG_ECDSA_SHA224, SIG_ECDSA_SHA256, SIG_ECDSA_SHA384, SIG_ECDSA_SHA512, stse_certificate_identify_ASN1_TLV(), TAG_OBJECT_IDENTIFIER, TAG_SEQUENCE, and SignatureAlgorithmOID_st::type.
stse_certificate_parse_ECC_public_key()
void stse_certificate_parse_ECC_public_key (const PLAT_UI8 * EccPK, stse_certificate_t * stse_certificate, const PLAT_UI8 ** next_thing)
Parse an ECC public Key from a certificate.
Parameters
[in] *EccPK pointer to the ECC public Key
[out] *stse_certificate pointer to the stse_certificate_t that will be filled
[out] **next_thing output pointer to next TLV
Definition at line 182 of file stse_certificate_subparsing.c.
References EC_bp256r1, EC_bp256t1, EC_bp384r1, EC_bp384t1, EC_bp512r1, EC_bp512t1, EC_P256, EC_P384, EC_P521, stse_internal_certificate::EllipticCurve, stse_cert_public_key_t::fsize, EllipticCurveOID_st::len, EllipticCurveOID_st::oid, stse_internal_certificate::pPubKey_point_representation_id, stse_internal_certificate::PubKey, stse_cert_public_key_t::pX, stse_cert_public_key_t::pY, stse_certificate_identify_ASN1_TLV(), TAG_BITSTRING, TAG_OBJECT_IDENTIFIER, TAG_SEQUENCE, and EllipticCurveOID_st::type.
stse_certificate_parse_integer()
void stse_certificate_parse_integer (const PLAT_UI8 * integer, const PLAT_UI8 ** outp, PLAT_I32 * outSize, const PLAT_UI8 ** next_thing)
Parse an ASN.1 INTEGER.
Parameters
[in] *integer pointer to the expected INTEGER TLV
[out] *outp will point to the starting byte of the integer
[out] *outSize will contain the size of the integer in bytes
[out] **next_thing will contain a pointer to the next TLV
Note
This doesn't copy the integer. To keep memory small this just returns a pointer to it.
Warning
only non-negative integers are supported
Definition at line 59 of file stse_certificate_subparsing.c.
References stse_certificate_identify_ASN1_TLV(), and TAG_INTEGER.
Referenced by stse_certificate_parse_ECDSA_signature().
stse_certificate_parse_validity()
void stse_certificate_parse_validity (const PLAT_UI8 * p, stse_cert_validity_t * notBefore_st, stse_cert_validity_t * notAfter_st, const PLAT_UI8 ** next_thing)
Parse the validity of a certificate.
Parameters
[in] *p pointer to the Name Attribute SET to be parsed
[out] *notBefore_st pointer to stse_cert_validity_t structure that will be filled with the "not before" date
[out] *notAfter_st pointer to stse_cert_validity_t structure that will be filled with the "not after" date
[out] **next_thing output pointer to next TLV
Note
In this function next_thing can be NULL
Definition at line 401 of file stse_certificate_subparsing.c.
References validity_st::days, validity_st::hours, validity_st::minutes, validity_st::month, validity_st::seconds, stse_certificate_identify_ASN1_TLV(), TAG_GeneralizedTime, TAG_SEQUENCE, TAG_UTCTime, and validity_st::year.
Referenced by stse_certificate_print_validity().
stse_certificate_parse_relative_distinguished_name()
void stse_certificate_parse_relative_distinguished_name (const PLAT_UI8 * p, const PLAT_UI8 ** nextRDN, const PLAT_UI8 ** attribute)
Parse an RelativeDistinguishedName.
Parameters
[in] *p pointer to the RelativeDistinguishedName (expeting a SET)
[out] **nextRDN output pointer to next RDN
[out] **attribute output pointer to RDN first attribute
Definition at line 285 of file stse_certificate_subparsing.c.
References stse_certificate_identify_ASN1_TLV().
stse_certificate_parse_attribute()
void stse_certificate_parse_attribute (const PLAT_UI8 * p, stse_cert_attribute_t * attribute_st, const PLAT_UI8 ** next_thing)
Parse a Name Attribute.
Parameters
[in] *p pointer to the AttributeTypeAndValue SEQUENCE to be parsed
[out] *attribute_st pointer to stse_cert_attribute_t structure that will be filled
[out] **next_thing output pointer to next TLV
Definition at line 345 of file stse_certificate_subparsing.c.
References attribute_st::str, attribute_st::strFormat, attribute_st::strSize, stse_certificate_identify_ASN1_TLV(), stse_certificate_identify_attribute(), TAG_OBJECT_IDENTIFIER, TAG_SEQUENCE, and attribute_st::type.
stse_certificate_date_compare()
PLAT_I32 stse_certificate_date_compare (const stse_cert_validity_t * D1, const stse_cert_validity_t * D2)
Compare two stse_cert_validity_t structures.
Parameters
[in] *D1 pointer to the first stse_cert_validity_t
[in] *D2 pointer to the second stse_cert_validity_t
Returns
Result of Comparison
Return values
-1 D1 < D2
0 D1 = D2
1 D1 > D2
Definition at line 461 of file stse_certificate_subparsing.c.
References validity_st::days, validity_st::hours, validity_st::minutes, validity_st::month, validity_st::seconds, and validity_st::year.
stse_certificate_count_attributes()
PLAT_I32 stse_certificate_count_attributes (const PLAT_UI8 * p)
Count the number of Attributes within a NAME.
Parameters
[in] *p pointer to the RDNSequence to be parsed \returun The number of Attributes
Definition at line 370 of file stse_certificate_subparsing.c.
References stse_certificate_identify_ASN1_TLV(), TAG_SEQUENCE, and TAG_SET.
stse_certificate_case_insensitive_compare()
PLAT_I32 stse_certificate_case_insensitive_compare (const PLAT_UI8 * p1, const PLAT_UI8 * p2, PLAT_I32 size)
String Comparison (case insensitive and for utf8)
Parameters
[in] *p1 first string to compare
[in] *p2 second string to compare
[in] size p1/p2 size
Returns
result of comparison
Return values
-1 strings are different
0 strings match
Definition at line 315 of file stse_certificate_subparsing.c.
stse_certificate_case_identify_extension()
PLAT_I32 stse_certificate_case_identify_extension (const PLAT_UI8 * oid, PLAT_I32 size)
Identify the Extension from its OID.
Parameters
[in] *oid The value of the OID of the Extension (got from stse_certificate_identify_ASN1_TLV)
[in] size size (in bytes) of the value field of this OID (got from stse_certificate_identify_ASN1_TLV)
Note
Only a very limited set of Extension is supported
Returns
The internal type identifing the Extension or -1 for failure
Definition at line 292 of file stse_certificate_subparsing.c.
References EXTENSION_BC, EXTENSION_EKU, EXTENSION_KU, ExtensionOID_st::len, ExtensionOID_st::oid, and ExtensionOID_st::type.
Referenced by stse_certificate_parse_extension().
stse_certificate_parse_extension()
void stse_certificate_parse_extension (const PLAT_UI8 * ext, PLAT_UI32 * extFlags, stse_cert_extension_t * ext_st)
Parse an x509 Extension.
Parameters
[in] *ext pointer to the extension
[out] extFlags pointer to a field extensionsFlags of an stse_certificate_t structure
[out] *ext_st pointer to an stse_cert_extension_t structure
Definition at line 514 of file stse_certificate_subparsing.c.
References extension_st::critical, EXTENSION_BC, EXTENSION_KU, stse_certificate_case_identify_extension(), stse_certificate_get_small_integer(), stse_certificate_identify_ASN1_TLV(), TAG_BITSTRING, TAG_BOOLEAN, TAG_INTEGER, TAG_OBJECT_IDENTIFIER, TAG_OCTETSTRING, TAG_SEQUENCE, extension_st::type, extension_st::value, and extension_st::valueSize.
stse_certificate_get_small_integer()
PLAT_I32 stse_certificate_get_small_integer (const PLAT_UI8 * value, PLAT_I32 size)
Reads the value of an INTEGER and returns it as a PLAT_I32.
Parameters
[in] *value pointer to the value field of an INTEGER TLV (got from stse_certificate_identify_ASN1_TLV)
[in] size size of the integer (got from stse_certificate_identify_ASN1_TLV)
Returns
the integer value as an PLAT_I32
Warning
only non-negative integers are supported
Definition at line 102 of file stse_certificate_subparsing.c.
Referenced by stse_certificate_parse_extension(), and stse_certificate_parse_X509_version().