STSAFE-A120_Accessory_authentication: STSE Certificate cryptography
STSE Certificate cryptography
STSecureElement Library » STSE Certificate
Functions
stse_ReturnCode_t stse_certificate_verify_signature (const stse_certificate_t *cert, const PLAT_UI8 *digest, PLAT_I32 digestSize, const PLAT_UI8 *signatureR, PLAT_I32 signatureRsize, const PLAT_UI8 *signatureS, PLAT_I32 signatureSsize)
stse_ReturnCode_t stse_certificate_verify_cert_signature (const stse_certificate_t *parent, const stse_certificate_t *child)
stse_ecc_key_type_t stse_certificate_get_key_type (const stse_certificate_t *cert)
stse_hash_algorithm_t stse_certificate_get_sig_hash_algo (const stse_certificate_t *cert)
Detailed Description
Function Documentation
stse_certificate_verify_signature()
stse_ReturnCode_t stse_certificate_verify_signature (const stse_certificate_t * cert, const PLAT_UI8 * digest, PLAT_I32 digestSize, const PLAT_UI8 * signatureR, PLAT_I32 signatureRsize, const PLAT_UI8 * signatureS, PLAT_I32 signatureSsize)
Verify the signature of a digest with a public key extracted from the certificate.
Parameters
[in] cert pointer to the parsed x509 certificate containing the public key to be used for the signature verification
[in] digest the digest of the message to be verified
[in] digestSize size in bytes of the digest of the message to be verified
[in] signatureR the R value of the signature to be verified
[in] signatureRsize the size in bytes of signatureR
[in] signatureS the S value of the signature to be verified
[in] signatureSsize the size in bytes of signatureS
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 63 of file stse_certificate_crypto.c.
References stse_certificate_get_key_type().
stse_certificate_verify_cert_signature()
stse_ReturnCode_t stse_certificate_verify_cert_signature (const stse_certificate_t * parent, const stse_certificate_t * child)
Check whether "parent" signed "child".
Parameters
[in] parent pointer to the parsed x509 certificate of the supposed issuer of child
[in] child pointer to the parsed x509 certificate of the certificated supposedly issued by parent
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 22 of file stse_certificate_crypto.c.
References stse_certificate_get_sig_hash_algo().
stse_certificate_get_key_type()
stse_ecc_key_type_t stse_certificate_get_key_type (const stse_certificate_t * cert)
Get the certificate public key type.
Parameters
[in] cert pointer to the parsed x509 certificate
Returns
stse_ecc_key_type_t : certificate public key type ; 0xFF if key type is invalid
Definition at line 144 of file stse_certificate_crypto.c.
References EC_P256, and stse_internal_certificate::EllipticCurve.
Referenced by stse_certificate_verify_signature(), and stse_device_authenticate().
stse_certificate_get_sig_hash_algo()
stse_hash_algorithm_t stse_certificate_get_sig_hash_algo (const stse_certificate_t * cert)
Get the certificate signature hash algorithm.
Parameters
[in] cert pointer to the parsed x509 certificate
Returns
stse_hash_algorithm_t : certificate signature hash algorithm ; 0xFF if hash algo is invalid
Definition at line 166 of file stse_certificate_crypto.c.
References SIG_ECDSA_SHA1, and stse_internal_certificate::SignatureAlgorithm.
Referenced by stse_certificate_verify_cert_signature().