STSAFE-A120_Accessory_authentication: AES
AES
STSecureElement Library » Services layer » STSAFE-Axxx
Functions
stse_ReturnCode_t stsafea_aes_ecb_encrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 *pPlaintext_message, PLAT_UI8 *pEncrypted_message)
stse_ReturnCode_t stsafea_aes_ecb_decrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pPlaintext_message)
stse_ReturnCode_t stsafea_aes_ccm_encrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 *pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pPlaintext_message, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pCounter_presence, PLAT_UI32 *pCounter)
stse_ReturnCode_t stsafea_aes_ccm_decrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 *pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pVerification_result, PLAT_UI8 *pPlaintext_message)
stse_ReturnCode_t stsafea_aes_gcm_encrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 *pIV, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pPlaintext_message, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag)
stse_ReturnCode_t stsafea_aes_gcm_decrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 *pIV, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pVerification_result, PLAT_UI8 *pPlaintext_message)
Detailed Description
Function Documentation
stsafea_aes_ecb_encrypt()
stse_ReturnCode_t stsafea_aes_ecb_encrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 * pPlaintext_message, PLAT_UI8 * pEncrypted_message)
Encrypt payload in AES ECB mode.
This service format and send encrypt command in AES ECB mode
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] message_length Length of the message
[in] pPlaintext_message Plaintext message to encrypt
[out] pEncrypted_message Encrypted message
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 20 of file stsafea_aes.c.
References STSAFEA_CMD_ENCRYPT, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stse_aes_ecb_encrypt().
stsafea_aes_ecb_decrypt()
stse_ReturnCode_t stsafea_aes_ecb_decrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pPlaintext_message)
Decrypt payload in AES ECB mode.
This service format and send decrypt command in AES ECB mode
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] message_length Length of the message
[in] pEncrypted_message Encrypted message to decrypt
[out] pPlaintext_message Plaintext message
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 107 of file stsafea_aes.c.
References STSAFEA_CMD_DECRYPT, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stse_aes_ecb_decrypt().
stsafea_aes_ccm_encrypt()
stse_ReturnCode_t stsafea_aes_ccm_encrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 * pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pPlaintext_message, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pCounter_presence, PLAT_UI32 * pCounter)
Encrypt payload in AES CCM* mode.
This service format and send encrypt command in AES CCM* mode
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] pNonce Buffer containing the nonce
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pPlaintext_message Buffer containing the message to encrypt
[out] pEncrypted_message Buffer to store the encrypted message
[out] pAuthentication_tag Buffer to store the authentication tag
[out] pCounter_presence Counter presence flag
[out] pCounter Buffer containing counter value if present
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 190 of file stsafea_aes.c.
References STSAFEA_CMD_ENCRYPT.
Referenced by stse_aes_ccm_encrypt().
stsafea_aes_ccm_decrypt()
stse_ReturnCode_t stsafea_aes_ccm_decrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 * pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pVerification_result, PLAT_UI8 * pPlaintext_message)
Decrypt payload in AES CCM* mode.
This service format and send decrypt command in AES CCM* mode
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] pNonce Buffer containing the nonce
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pEncrypted_message Buffer containing the message to decrypt
[in] pAuthentication_tag Buffer containing the authentication tag
[out] pVerification_result Verification result flag
[out] pPlaintext_message Buffer to store the decrypted message
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 305 of file stsafea_aes.c.
References STSAFEA_CMD_DECRYPT, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stse_aes_ccm_decrypt().
stsafea_aes_gcm_encrypt()
stse_ReturnCode_t stsafea_aes_gcm_encrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 * pIV, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pPlaintext_message, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag)
Encrypt payload in AES GCM mode.
This service format and send encrypt command in AES GCM mode
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] IV_length IV buffer length in bytes
[in] IV IV buffer
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pPlaintext_message Buffer containing the message to encrypt
[out] pEncrypted_message Buffer to store the encrypted message
[out] pAuthentication_tag Buffer to store the authentication tag
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 404 of file stsafea_aes.c.
References STSAFEA_CMD_ENCRYPT, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stsafea_aes_gmac_compute(), and stse_aes_gcm_encrypt().
stsafea_aes_gcm_decrypt()
stse_ReturnCode_t stsafea_aes_gcm_decrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 * pIV, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pVerification_result, PLAT_UI8 * pPlaintext_message)
Decrypt payload in AES GCM mode.
This service format and send decrypt command in AES GCM mode
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] IV_length IV buffer length in bytes
[in] IV IV buffer
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pEncrypted_message Buffer containing the message to decrypt
[in] pAuthentication_tag Buffer containing the authentication tag
[out] pVerification_result Verification result flag
[out] pPlaintext_message Buffer to store the decrypted message
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 508 of file stsafea_aes.c.
References STSAFEA_CMD_DECRYPT, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stsafea_aes_gmac_verify(), and stse_aes_gcm_decrypt().