STSAFE-A120_Accessory_authentication: STSE AES cryptography
STSE AES cryptography
STSecureElement Library » API layer
Functions
stse_ReturnCode_t stse_aes_ecb_encrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 *pPlaintext_message, PLAT_UI8 *pEncrypted_message)
stse_ReturnCode_t stse_aes_ecb_decrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pPlaintext_message)
stse_ReturnCode_t stse_aes_ccm_encrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 *pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pPlaintext_message, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pCounter_presence, PLAT_UI32 *pCounter)
stse_ReturnCode_t stse_aes_ccm_decrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 *pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pVerification_result, PLAT_UI8 *pPlaintext_message)
stse_ReturnCode_t stse_aes_gcm_encrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 *pIV, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pPlaintext_message, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag)
stse_ReturnCode_t stse_aes_gcm_decrypt (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 *pIV, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 *pEncrypted_message, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pVerification_result, PLAT_UI8 *pPlaintext_message)
Detailed Description
The data storage API set provides high level functions to manage Access to the Secure User NVM of STSAFE devices.
Function Documentation
stse_aes_ecb_encrypt()
stse_ReturnCode_t stse_aes_ecb_encrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 * pPlaintext_message, PLAT_UI8 * pEncrypted_message)
Encrypt payload in AES ECB mode.
This API encrypt payload in AES ECB mode using the specified key from STSAFE symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] message_length Length of the message
[in] pPlaintext_message Plaintext message to encrypt
[out] pEncrypted_message Encrypted message
Returns
stse_ReturnCode_t : STSAFE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSE device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stse_ReturnCode_t ret;
PLAT_UI8 slot_number = 0;
PLAT_UI8 message[] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                      0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F};
PLAT_UI8 output[sizeof(message)];
ret = stse_aes_ecb_encrypt(pStse_handler,
    slot_number,
    sizeof(message),
    message,
    output);
if(ret != STSE_OK)
{
    /* Handle Error */
}
See also
stse_init
Definition at line 20 of file stse_aes.c.
References stsafea_aes_ecb_encrypt(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_aes_ecb_decrypt()
stse_ReturnCode_t stse_aes_ecb_decrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI16 message_length, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pPlaintext_message)
Decrypt payload in AES ECB mode.
This API decrypt payload in AES ECB mode using the specified key from STSAFE symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] message_length Length of the message
[in] pEncrypted_message Encrypted message to decrypt
[out] pPlaintext_message Plaintext message
Returns
stse_ReturnCode_t : STSAFE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSE device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stse_ReturnCode_t ret;
PLAT_UI8 slot_number = 0;
PLAT_UI8 ciphertext[] = {0x27, 0x9F, 0xB7, 0x4A, 0x75, 0x72, 0x13, 0x5E,
                         0x8F, 0x9B, 0x8E, 0xF6, 0xD1, 0xEE, 0xE0, 0x03};
PLAT_UI8 output[sizeof(ciphertext)];
ret = stse_aes_ecb_decrypt(pStse_handler,
    slot_number,
    sizeof(ciphertext),
    ciphertext,
    output);
if(ret != STSE_OK)
{
    /* Handle Error */
}
See also
stse_init
Definition at line 40 of file stse_aes.c.
References stsafea_aes_ecb_decrypt(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_aes_ccm_encrypt()
stse_ReturnCode_t stse_aes_ccm_encrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 * pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pPlaintext_message, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pCounter_presence, PLAT_UI32 * pCounter)
Encrypt payload in AES CCM* mode.
This API Encrypt payload in AES CCM* mode using the specified key from STSAFE symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] pNonce Buffer containing the nonce
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pPlaintext_message Buffer containing the message to encrypt
[out] pEncrypted_message Buffer to store the encrypted message
[out] pAuthentication_tag Buffer to store the authentication tag
[out] pCounter_presence Counter presence flag
[out] pCounter Buffer containing counter value if present
Returns
stse_ReturnCode_t : STSAFE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSE device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stse_ReturnCode_t ret;
PLAT_UI8 associated_data[]      = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
PLAT_UI8 associated_data_length = 8;
PLAT_UI8 plaintext[]            = {0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
                                   0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
                                   0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F};
PLAT_UI8 plaintextLength        = 24;
PLAT_UI8 nonce[]                = {0x00, 0x00, 0x00, 0x04, 0x03, 0x02, 0x01, 0xA0,
                                   0xA1, 0xA2, 0xA3, 0xA4, 0xA5};
PLAT_UI8 macLength              = 8;
PLAT_UI8 mac[macLength];
PLAT_UI8 ciphertext[plaintextLength];
ret = stse_aes_ccm_encrypt(
        pStse_handler,
        slot_number,
        macLength,
        nonce,
        associated_data_length,
        associated_data,
        plaintextLength,
        plaintext,
        ciphertext,
        mac,
        NULL,  // No counter
        NULL); // No counter
if(ret != STSE_OK)
{
    /* Handle Error */
}
See also
stse_init
Definition at line 60 of file stse_aes.c.
References stsafea_aes_ccm_encrypt(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_aes_ccm_decrypt()
stse_ReturnCode_t stse_aes_ccm_decrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI8 * pNonce, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pVerification_result, PLAT_UI8 * pPlaintext_message)
Decrypt payload in AES CCM* mode.
This API Decrypt payload in AES CCM* mode using the specified key from STSAFE symmetric key table
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] pNonce Buffer containing the nonce
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pEncrypted_message Buffer containing the message to decrypt
[in] pAuthentication_tag Buffer containing the authentication tag
[out] pVerification_result Verification result flag
[out] pPlaintext_message Buffer to store the decrypted message
Returns
stse_ReturnCode_t : STSAFE_OK on success ; error code otherwise
Description Following diagram illustrates the interactions performed between the Host and the target STSE device during the API execution
Use-case example
The following applicative code snippet illustrates how to use this API function in main application.
stse_ReturnCode_t ret;
PLAT_UI8 associated_data[]      = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
PLAT_UI8 associated_data_length = 8;
PLAT_UI8 plaintextLength        = 24;
PLAT_UI8 nonce[]                = {0x00, 0x00, 0x00, 0x04, 0x03, 0x02, 0x01, 0xA0,
                                   0xA1, 0xA2, 0xA3, 0xA4, 0xA5};
PLAT_UI8 mac[]                  = {0xA0, 0x91, 0xD5, 0x6E, 0x10, 0x40, 0x09, 0x16};
PLAT_UI8 macLength              = 8;
PLAT_UI8 ciphertext[]           = {0x72, 0xC9, 0x1A, 0x36, 0xE1, 0x35, 0xF8, 0xCF,
                                   0x29, 0x1C, 0xA8, 0x94, 0x08, 0x5C, 0x87, 0xE3,
                                   0xCC, 0x15, 0xC4, 0x39, 0xC9, 0xE4, 0x3A, 0x3B};
PLAT_UI8 verification_result    = 0;
PLAT_UI8 plaintext[plaintextLength];
ret = stse_aes_ccm_decrypt(pStse_handler,
        slot_number,
        macLength,
        nonce,
        associated_data_length,
        associated_data,
        plaintextLength,
        ciphertext,
        mac,
        &verification_result,
        plaintext);
if(ret != STSE_OK)
{
    /* Handle Error */
}
See also
stse_init
Definition at line 94 of file stse_aes.c.
References stsafea_aes_ccm_decrypt(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_aes_gcm_encrypt()
stse_ReturnCode_t stse_aes_gcm_encrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 * pIV, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pPlaintext_message, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag)
Encrypt payload in AES CCM mode.
This API Encrypt payload in AES GCM mode using the specified key from STSAFE symmetric key table
Parameters
[in] pSTSE Pointer to STSE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] IV_length IV buffer length in bytes
[in] IV IV buffer
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pPlaintext_message Buffer containing the message to encrypt
[out] pEncrypted_message Buffer to store the encrypted message
[out] pAuthentication_tag Buffer to store the authentication tag
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 126 of file stse_aes.c.
References stsafea_aes_gcm_encrypt(), and STSE_API_HANDLER_NOT_INITIALISED.
stse_aes_gcm_decrypt()
stse_ReturnCode_t stse_aes_gcm_decrypt (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 authentication_tag_length, PLAT_UI16 IV_length, PLAT_UI8 * pIV, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI16 message_length, PLAT_UI8 * pEncrypted_message, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pVerification_result, PLAT_UI8 * pPlaintext_message)
Decrypt payload in AES GCM mode.
This API Decrypt payload in AES GCM mode using the specified key from STSAFE symmetric key table
Parameters
[in] pSTSE Pointer to STSE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] authentication_tag_length Expected length for the authentication tag
[in] IV_length IV buffer length in bytes
[in] IV IV buffer
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] message_length Length of the message to encrypt
[in] pEncrypted_message Buffer containing the message to decrypt
[in] pAuthentication_tag Buffer containing the authentication tag
[out] pVerification_result Verification result flag
[out] pPlaintext_message Buffer to store the decrypted message
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 158 of file stse_aes.c.
References stsafea_aes_gcm_decrypt(), and STSE_API_HANDLER_NOT_INITIALISED.