STSAFE-A120_Accessory_authentication: Platform Abstraction Layer (PAL)
Platform Abstraction Layer (PAL)
STSecureElement Library » Core layer
Functions
PLAT_UI16 stse_platform_Crc16_Calculate (PLAT_UI8 *pbuffer, PLAT_UI16 length)
PLAT_UI16 stse_platform_Crc16_Accumulate (PLAT_UI8 *pbuffer, PLAT_UI16 length)
void stse_platform_Delay_ms (PLAT_UI32 delay_val)
void stse_platform_timeout_ms_start (PLAT_UI16 timeout_val)
PLAT_UI8 stse_platform_timeout_ms_get_status (void)
stse_ReturnCode_t stse_platform_nvm_write (PLAT_UI32 nvmAddr, PLAT_UI32 bufferAddr, PLAT_UI32 bufferLength)
PLAT_UI32 stse_platform_Random (void)
stse_ReturnCode_t stse_platform_aes_cmac_compute (const PLAT_UI8 *pPayload, PLAT_UI16 payload_length, const PLAT_UI8 *pKey, PLAT_UI16 key_length, PLAT_UI16 exp_tag_size, PLAT_UI8 *pTag, PLAT_UI16 *pTag_length)
stse_ReturnCode_t stse_platform_aes_cmac_verify (const PLAT_UI8 *pPayload, PLAT_UI16 payload_length, const PLAT_UI8 *pKey, PLAT_UI16 key_length, const PLAT_UI8 *pTag, PLAT_UI16 tag_length)
stse_ReturnCode_t stse_platform_aes_ccm_enc (const PLAT_UI8 *pPlaintext, PLAT_UI16 plaintext_length, const PLAT_UI8 *pKey, PLAT_UI16 key_length, const PLAT_UI8 *pNonce, PLAT_UI16 nonce_length, const PLAT_UI8 *pAssocData, PLAT_UI16 assocData_length, PLAT_UI8 *pEncryptedtext, PLAT_UI16 *pEncryptedtext_length, PLAT_UI8 *pTag, PLAT_UI16 tag_length)
stse_ReturnCode_t stse_platform_aes_ccm_dec (const PLAT_UI8 *pEncryptedtext, PLAT_UI16 encryptedtext_length, const PLAT_UI8 *pTag, PLAT_UI16 tag_length, const PLAT_UI8 *pKey, PLAT_UI16 key_length, const PLAT_UI8 *pNonce, PLAT_UI16 nonce_length, const PLAT_UI8 *pAssocData, PLAT_UI16 assocData_length, const PLAT_UI8 *pPlaintext, PLAT_UI16 plaintext_length)
stse_ReturnCode_t stse_platform_aes_cbc_enc (const PLAT_UI8 *pPlaintext, PLAT_UI16 plaintext_length, PLAT_UI8 *pInitial_value, const PLAT_UI8 *pKey, PLAT_UI16 key_length, PLAT_UI8 *pEncryptedtext, PLAT_UI16 *pEncryptedtext_length)
stse_ReturnCode_t stse_platform_aes_cbc_dec (const PLAT_UI8 *pEncryptedtext, PLAT_UI16 encryptedtext_length, PLAT_UI8 *pInitial_value, const PLAT_UI8 *pKey, PLAT_UI16 key_length, PLAT_UI8 *pPlaintext, PLAT_UI16 *pPlaintext_length)
stse_ReturnCode_t stse_platform_aes_ecb_enc (const PLAT_UI8 *pPlaintext, PLAT_UI16 plaintext_length, const PLAT_UI8 *pKey, PLAT_UI16 key_length, PLAT_UI8 *pEncryptedtext, PLAT_UI16 *pEncryptedtext_length)
stse_ReturnCode_t stse_platform_aes_ecb_dec (const PLAT_UI8 *pEncryptedtext, PLAT_UI16 encryptedtext_length, const PLAT_UI8 *pKey, PLAT_UI16 key_length, PLAT_UI8 *pPlaintext, PLAT_UI16 *pPlaintext_length)
stse_ReturnCode_t stse_platform_nist_kw_encrypt (PLAT_UI8 *pPayload, PLAT_UI32 payload_length, PLAT_UI8 *pKey, PLAT_UI8 key_length, PLAT_UI8 *pOutput, PLAT_UI32 *pOutput_length)
stse_ReturnCode_t stse_platform_hmac_sha256_compute (PLAT_UI8 *pSalt, PLAT_UI16 salt_length, PLAT_UI8 *pInput_keying_material, PLAT_UI16 input_keying_material_length, PLAT_UI8 *pInfo, PLAT_UI16 info_length, PLAT_UI8 *pOutput_keying_material, PLAT_UI16 output_keying_material_length)
stse_ReturnCode_t stse_platform_hmac_sha256_extract (PLAT_UI8 *pSalt, PLAT_UI16 salt_length, PLAT_UI8 *pInput_keying_material, PLAT_UI16 input_keying_material_length, PLAT_UI8 *pPseudorandom_key, PLAT_UI16 pseudorandom_key_expected_length)
stse_ReturnCode_t stse_platform_hmac_sha256_expand (PLAT_UI8 *pPseudorandom_key, PLAT_UI16 pseudorandom_key_length, PLAT_UI8 *pInfo, PLAT_UI16 info_length, PLAT_UI8 *pOutput_keying_material, PLAT_UI16 output_keying_material_length)
stse_ReturnCode_t stse_platform_hash_sha256_compute (PLAT_UI8 *pPayload, PLAT_UI32 payload_length, PLAT_UI8 *pHash, PLAT_UI32 hash_length)
stse_ReturnCode_t stse_platform_power_on (PLAT_UI8 busID, PLAT_UI8 devAddr)
stse_ReturnCode_t stse_platform_power_off (PLAT_UI8 busID, PLAT_UI8 devAddr)
Detailed Description
The STSAFE Middleware Platform Abstraction Layer gather all functions used for adapting the Platform specific Hardware and Software .
The function declared in the middleware platform abstraction layer must be adaped by the system developer to fit with target application HW/SW specificty . Please refer to PAL function description to get more details on expected function behavior and recommended implementation
Function Documentation
stse_platform_Crc16_Calculate()
PLAT_UI16 stse_platform_Crc16_Calculate (PLAT_UI8 * pbuffer, PLAT_UI16 length)
Compute a 16-bit crc value on specific 8-bit buffer of buffer length.
Parameters
[in] pbuffer pointer to crc input buffer
[in] length input buffer length
Returns
16-bit CRC value
stse_platform_Crc16_Accumulate()
PLAT_UI16 stse_platform_Crc16_Accumulate (PLAT_UI8 * pbuffer, PLAT_UI16 length)
Accumulate an 8-bit buffer of buffer length in crc unit.
Parameters
[in] pbuffer pointer to crc input buffer
[in] length input buffer length
Returns
16-bit CRC value
stse_platform_Delay_ms()
void stse_platform_Delay_ms (PLAT_UI32 delay_val)
Perform a delay of "delay_val" ms.
Parameters
[in] delay_val length of the delay in milliseconds
Returns
None
stse_platform_timeout_ms_start()
void stse_platform_timeout_ms_start (PLAT_UI16 timeout_val)
Start a timeout counter of "timeout_val" ms.
Parameters
[in] timeout_val length of the timeout in milliseconds
Returns
None
stse_platform_timeout_ms_get_status()
PLAT_UI8 stse_platform_timeout_ms_get_status (void)
Return timeout status.
Returns
0 if the timeout counter is still running 1 if the timeout was excedeed
stse_platform_nvm_write()
stse_ReturnCode_t stse_platform_nvm_write (PLAT_UI32 nvmAddr, PLAT_UI32 bufferAddr, PLAT_UI32 bufferLength)
Write data from input buffer into Non Volatile Memory.
Parameters
[in] nvmAddr PLAT_UI32 address in NVM
[in] bufferAddr pointer to input buffer
[in] bufferLength input buffer length
Returns
None
stse_platform_Random()
PLAT_UI32 stse_platform_Random (void)
Generate a PLAT_UI32 random number.
Returns
32-bit random number
stse_platform_aes_cmac_compute()
stse_ReturnCode_t stse_platform_aes_cmac_compute (const PLAT_UI8 * pPayload, PLAT_UI16 payload_length, const PLAT_UI8 * pKey, PLAT_UI16 key_length, PLAT_UI16 exp_tag_size, PLAT_UI8 * pTag, PLAT_UI16 * pTag_length)
Perform an AES CMAC encryption.
Parameters
[in] *pPayload Pointer to Payload
[in] payload_length Length of the payload in byte
[in] *pKey Pointer to key
[in] key_length Length of the key in byte
[in] exp_tag_size Expected tag size in byte
[out] *pTag Pointer to Tag
[out] *pTag_length Pointer to Tag length value output
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_aes_cmac_verify()
stse_ReturnCode_t stse_platform_aes_cmac_verify (const PLAT_UI8 * pPayload, PLAT_UI16 payload_length, const PLAT_UI8 * pKey, PLAT_UI16 key_length, const PLAT_UI8 * pTag, PLAT_UI16 tag_length)
Perform an AES CMAC decryption.
Parameters
[in] *pPayload Pointer to Payload
[in] payload_length Length of the payload in byte
[in] *pKey Pointer to key
[in] key_length Length of the key in byte
[in] *pTag Pointer to Tag
[in] tag_length Pointer to Tag length value output
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_aes_ccm_enc()
stse_ReturnCode_t stse_platform_aes_ccm_enc (const PLAT_UI8 * pPlaintext, PLAT_UI16 plaintext_length, const PLAT_UI8 * pKey, PLAT_UI16 key_length, const PLAT_UI8 * pNonce, PLAT_UI16 nonce_length, const PLAT_UI8 * pAssocData, PLAT_UI16 assocData_length, PLAT_UI8 * pEncryptedtext, PLAT_UI16 * pEncryptedtext_length, PLAT_UI8 * pTag, PLAT_UI16 tag_length)
Perform an AES CCM encryption.
Parameters
[in] *pPlaintext Pointer to the plaintext data
[in] plaintext_length Length of the plaintext data
[in] *pKey Pointer to the key
[in] key_length Length of the key
[in] *pNonce Pointer to Nonce
[in] nonce_length Length of the Nonce
[in] *pAssocData Pointer to Associated Data
[in] assocData_length Length of the Associated Data
[out] *pEncryptedtext Pointer to the encrypted payload
[out] *pEncryptedtext_length Length of encrypted payload
[out] *pTag Pointer to the tag
[out] tag_length Length of the tag
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_aes_ccm_dec()
stse_ReturnCode_t stse_platform_aes_ccm_dec (const PLAT_UI8 * pEncryptedtext, PLAT_UI16 encryptedtext_length, const PLAT_UI8 * pTag, PLAT_UI16 tag_length, const PLAT_UI8 * pKey, PLAT_UI16 key_length, const PLAT_UI8 * pNonce, PLAT_UI16 nonce_length, const PLAT_UI8 * pAssocData, PLAT_UI16 assocData_length, const PLAT_UI8 * pPlaintext, PLAT_UI16 plaintext_length)
Parameters
[in] *pEncryptedtext Pointer to the encrypted payload
[in] encryptedtext_length Length of encrypted payload
[in] *pTag Pointer to the tag
[in] tag_length Length of the tag
[in] *pKey pointer to the key
[in] key_length Length of the key
[in] *pNonce pointer to Nonce
[in] nonce_length Length of the Nonce
[in] *pAssocData pointer to Associated Data
[in] assocData_length Length of the Associated Data
[out] *pPlaintext pointer to PlainText payload
[out] plaintext_length Length of the PlainText payload
Returns
stse_platform_aes_cbc_enc()
stse_ReturnCode_t stse_platform_aes_cbc_enc (const PLAT_UI8 * pPlaintext, PLAT_UI16 plaintext_length, PLAT_UI8 * pInitial_value, const PLAT_UI8 * pKey, PLAT_UI16 key_length, PLAT_UI8 * pEncryptedtext, PLAT_UI16 * pEncryptedtext_length)
Perform an AES CBC encryption.
Parameters
[in] pPlaintext Pointer to the plaintext data
[in] plaintext_length Length of the plaintext data
[in] pInitial_value Pointer to encryption IV
[in] pKey Pointer to the key
[in] key_length Length of the key
[out] pEncryptedtext Pointer to the encrypted payload
[out] pEncryptedtext_length Length of encrypted payload
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_aes_cbc_dec()
stse_ReturnCode_t stse_platform_aes_cbc_dec (const PLAT_UI8 * pEncryptedtext, PLAT_UI16 encryptedtext_length, PLAT_UI8 * pInitial_value, const PLAT_UI8 * pKey, PLAT_UI16 key_length, PLAT_UI8 * pPlaintext, PLAT_UI16 * pPlaintext_length)
Perform an AES CBC decryption.
Parameters
[in] pEncryptedtext Pointer to the encrypted payload
[in] encryptedtext_length Length of encrypted payload
[in] pInitial_value Pointer to decryption IV
[in] pKey pointer to the key
[in] key_length Length of the key
[out] pPlaintext pointer to PlainText payload
[out] pPlaintext_length Length of the PlainText payload
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_aes_ecb_enc()
stse_ReturnCode_t stse_platform_aes_ecb_enc (const PLAT_UI8 * pPlaintext, PLAT_UI16 plaintext_length, const PLAT_UI8 * pKey, PLAT_UI16 key_length, PLAT_UI8 * pEncryptedtext, PLAT_UI16 * pEncryptedtext_length)
Perform an AES ECB encryption.
Parameters
[in] pPlaintext Pointer to the plaintext data
[in] plaintext_length Length of the plaintext data
[in] pKey Pointer to the key
[in] key_length Length of the key
[out] pEncryptedtext Pointer to the encrypted payload
[out] pEncryptedtext_length Length of encrypted payload
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_aes_ecb_dec()
stse_ReturnCode_t stse_platform_aes_ecb_dec (const PLAT_UI8 * pEncryptedtext, PLAT_UI16 encryptedtext_length, const PLAT_UI8 * pKey, PLAT_UI16 key_length, PLAT_UI8 * pPlaintext, PLAT_UI16 * pPlaintext_length)
Perform an AES ECB decryption.
Parameters
[in] pEncryptedtext Pointer to the encrypted payload
[in] encryptedtext_length Length of encrypted payload
[in] pKey pointer to the key
[in] key_length Length of the key
[out] pPlaintext pointer to PlainText payload
[out] pPlaintext_length Length of the PlainText payload
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_nist_kw_encrypt()
stse_ReturnCode_t stse_platform_nist_kw_encrypt (PLAT_UI8 * pPayload, PLAT_UI32 payload_length, PLAT_UI8 * pKey, PLAT_UI8 key_length, PLAT_UI8 * pOutput, PLAT_UI32 * pOutput_length)
Perform a NIST KW (keywrap) encrypt.
Parameters
[in] pPayload Pointer to payload
[in] payload_length Length of payload
[in] pKey Pointer to the key
[in] key_length Length of the key
[out] pOutput Pointer to encrypted output
[out] pOutput_length Length of the encrypted output
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_hmac_sha256_compute()
stse_ReturnCode_t stse_platform_hmac_sha256_compute (PLAT_UI8 * pSalt, PLAT_UI16 salt_length, PLAT_UI8 * pInput_keying_material, PLAT_UI16 input_keying_material_length, PLAT_UI8 * pInfo, PLAT_UI16 info_length, PLAT_UI8 * pOutput_keying_material, PLAT_UI16 output_keying_material_length)
Perform an HMAC Key derivation using HMAC extract then HMAC expand functions (cf. RFC 5869)
Parameters
[in] pSalt HMAC salt
[in] salt_length HMAC salt length
[in] pInput_keying_material Input keying material (IKM), could be ECDH output
[in] input_keying_material_length Input keying material length
[in] pInfo Application specific information
[in] info_length Information length
[out] pOutput_keying_material Output keying material (OKM)
[in] output_keying_material_length Output keying material expected length
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 31 of file stse_platform.c.
References STSAFEA_SHA_256_HASH_SIZE, stse_platform_hmac_sha256_expand(), and stse_platform_hmac_sha256_extract().
stse_platform_hmac_sha256_extract()
stse_ReturnCode_t stse_platform_hmac_sha256_extract (PLAT_UI8 * pSalt, PLAT_UI16 salt_length, PLAT_UI8 * pInput_keying_material, PLAT_UI16 input_keying_material_length, PLAT_UI8 * pPseudorandom_key, PLAT_UI16 pseudorandom_key_expected_length)
Perform an HMAC extract using SHA256 (cf. RFC 5869)
Parameters
[in] pSalt HMAC salt
[in] salt_length HMAC salt length
[in] pInput_keying_material Input keying material (IKM), could be ECDH output
[in] input_keying_material_length Input keying material length
[out] pPseudorandom_key Pseudorandom key (PRK)
[in] pseudorandom_key_expected_length Pseudorandom key length
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Referenced by stse_platform_hmac_sha256_compute().
stse_platform_hmac_sha256_expand()
stse_ReturnCode_t stse_platform_hmac_sha256_expand (PLAT_UI8 * pPseudorandom_key, PLAT_UI16 pseudorandom_key_length, PLAT_UI8 * pInfo, PLAT_UI16 info_length, PLAT_UI8 * pOutput_keying_material, PLAT_UI16 output_keying_material_length)
Perform an HMAC expand using SHA256 (cf. RFC 5869)
Parameters
[in] pPseudorandom_key Pseudorandom key (PRK)
[in] pseudorandom_key_length Pseudorandom key length
[in] pInfo Application specific information
[in] info_length Information length
[out] pOutput_keying_material Output keying material (OKM)
[in] output_keying_material_length Output keying material expected length
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Referenced by stse_platform_hmac_sha256_compute().
stse_platform_hash_sha256_compute()
stse_ReturnCode_t stse_platform_hash_sha256_compute (PLAT_UI8 * pPayload, PLAT_UI32 payload_length, PLAT_UI8 * pHash, PLAT_UI32 hash_length)
Perform an HASH using SHA256.
Parameters
[in] pPayload Payload to hash
[in] payload_length Payload length
[out] pHash Hash output buffer
[in] hash_length Expected hash length
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
stse_platform_power_on()
stse_ReturnCode_t stse_platform_power_on (PLAT_UI8 busID, PLAT_UI8 devAddr)
Platform Abstraction function for target STSAFE power-on.
Parameters
[in] busID Target STSAFE bus ID
[in] devAddr Target STSAFE device address
stse_platform_power_off()
stse_ReturnCode_t stse_platform_power_off (PLAT_UI8 busID, PLAT_UI8 devAddr)
Platform Abstraction function for target STSAFE power-off.
Parameters
[in] busID Target STSAFE bus ID
[in] devAddr Target STSAFE device address