STSAFE-A120_Accessory_authentication: MAC
MAC
STSecureElement Library » Services layer » STSAFE-Axxx
Functions
stse_ReturnCode_t stsafea_cmac_hmac_compute (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 *pMessage, PLAT_UI8 message_length, PLAT_UI8 *pMac, PLAT_UI8 mac_length)
stse_ReturnCode_t stsafea_cmac_hmac_verify (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI8 *pMac, PLAT_UI8 mac_length, PLAT_UI8 *pMessage, PLAT_UI8 message_length, PLAT_UI8 *verification_result)
stse_ReturnCode_t stsafea_aes_gmac_compute (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI16 IV_length, PLAT_UI8 *pIV, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI8 authentication_tag_length, PLAT_UI8 *pAuthentication_tag)
stse_ReturnCode_t stsafea_aes_gmac_verify (stse_Handler_t *pSTSE, PLAT_UI8 slot_number, PLAT_UI16 IV_length, PLAT_UI8 *pIV, PLAT_UI16 associated_data_length, PLAT_UI8 *pAssociated_data, PLAT_UI8 authentication_tag_length, PLAT_UI8 *pAuthentication_tag, PLAT_UI8 *pVerification_result)
Detailed Description
Function Documentation
stsafea_cmac_hmac_compute()
stse_ReturnCode_t stsafea_cmac_hmac_compute (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 * pMessage, PLAT_UI8 message_length, PLAT_UI8 * pMac, PLAT_UI8 mac_length)
Generate a CMAC.
This service format and send Generate CMAC command
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] pMessage Plaintext message
[in] message_length Plaintext message length
[out] pMac Buffer to store the MAC
[out] mac_length MAC length (CMAC:2,4,8,16 / HMAC:16-32)
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 20 of file stsafea_mac.c.
References STSAFEA_CMD_GENERATE_MAC, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stse_cmac_hmac_compute().
stsafea_cmac_hmac_verify()
stse_ReturnCode_t stsafea_cmac_hmac_verify (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI8 * pMac, PLAT_UI8 mac_length, PLAT_UI8 * pMessage, PLAT_UI8 message_length, PLAT_UI8 * verification_result)
Verify a CMAC.
This service format and send Verify CMAC command
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] pMac Buffer containing the MAC
[in] mac_length MAC length (CMAC:2,4,8,16 / HMAC:16-32)
[in] pMessage Plaintext message
[in] message_length Plaintext message length
[out] verification_result Verification result flag
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 98 of file stsafea_mac.c.
References STSAFEA_CMD_VERIFY_MAC, STSE_SERVICE_HANDLER_NOT_INITIALISED, and STSE_SERVICE_INVALID_PARAMETER.
Referenced by stse_cmac_hmac_verify().
stsafea_aes_gmac_compute()
stse_ReturnCode_t stsafea_aes_gmac_compute (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI16 IV_length, PLAT_UI8 * pIV, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI8 authentication_tag_length, PLAT_UI8 * pAuthentication_tag)
Generate a GMAC.
This service format and send Generate GMAC command
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] IV_length IV buffer length in bytes
[in] IV IV buffer
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] authentication_tag_length Expected length for the authentication tag
[out] pAuthentication_tag Buffer to store the authentication tag
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 180 of file stsafea_mac.c.
References stsafea_aes_gcm_encrypt(), and STSE_SERVICE_HANDLER_NOT_INITIALISED.
Referenced by stse_aes_gmac_compute().
stsafea_aes_gmac_verify()
stse_ReturnCode_t stsafea_aes_gmac_verify (stse_Handler_t * pSTSE, PLAT_UI8 slot_number, PLAT_UI16 IV_length, PLAT_UI8 * pIV, PLAT_UI16 associated_data_length, PLAT_UI8 * pAssociated_data, PLAT_UI8 authentication_tag_length, PLAT_UI8 * pAuthentication_tag, PLAT_UI8 * pVerification_result)
Verify a GMAC.
This service format and send Verify GMAC command
Parameters
[in] pSTSE Pointer to STSAFE Handler
[in] slot_number Key slot in symmetric key table to be used
[in] IV_length IV buffer length in bytes
[in] IV IV buffer
[in] associated_data_length Length of the associated data
[in] pAssociated_data Buffer containing associated data
[in] authentication_tag_length Expected length for the authentication tag
[in] pAuthentication_tag Buffer containing the authentication tag
[out] pVerification_result Verification result flag
Returns
stse_ReturnCode_t : STSE_OK on success ; error code otherwise
Definition at line 209 of file stsafea_mac.c.
References stsafea_aes_gcm_decrypt(), and STSE_SERVICE_HANDLER_NOT_INITIALISED.
Referenced by stse_aes_gmac_verify().